// <auto-generated />
namespace Trabalho_2_webForms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INicial));
        
        string IMigrationMetadata.Id
        {
            get { return "202205281624058_INicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
