<%@ Page Title="Listagem Serviços" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Listagem.aspx.cs" Inherits="Trabalho_2_webForms.Paginas.Servicos.Listagem" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <fieldset class="titulo-pagina">
        <legend><%: Title %></legend>
        <div class="row">
            <div class="col-12">
                <a runat="server" class="btn btn-btn-default" href="~/Paginas/Servicos/Cadastro.aspx">Novo Serviço</a>
            </div>
        </div>
        <asp:GridView ID="grdDados" 
            runat="server" 
            AutoGenerateColumns="false" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true"
            OnRowDeleting="grdDados_RowDeleting" 
            OnRowEditing="grdDados_RowEditing"
            CssClass="table table-striped table-bordered">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Codigo" />
                <asp:BoundField DataField="Nome" HeaderText="Nome" />
                <asp:BoundField DataField="Descricao" HeaderText="Descrição" />
                <asp:BoundField DataField="ValorUnitario" HeaderText="Valor Unitario" />
            </Columns>
        </asp:GridView>
    </fieldset>
</asp:Content>
